@baseUrl =  http://localhost:3000/api/artists  

# User API

# @name Getall
GET {{baseUrl}}


###
# @name GetbyId
GET {{baseUrl}}/64c9ee2f999d05165d828c68

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
"name": "demo",
"genres": ["64c9ee2f999d05165d828c68"],
"artistId": "64c9ee2f999d05165d828c68"
}

###

# @name Update
PUT {{baseUrl}}/update/64d364bcf1daaf1c65c96395
Content-Type: application/json

{
   "name": "demo mới"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64d364bcf1daaf1c65c96395

###
###
# @name DeleteMany
POST {{baseUrl}}/delete-many
Content-Type: application/json

{
    "ids": [
        "64cb784edbeafd46df22e8b1",
        ]
}

###
# @name Trash
GET {{baseUrl}}/trash

###
# @name Restore
PATCH {{baseUrl}}/restore/64d364bcf1daaf1c65c96395

###
# @name ForceDelete
DELETE {{baseUrl}}/force/64d364b5f1daaf1c65c96392
