@baseUrl =  http://localhost:3000/api/songs

# User API

# @name Getall
GET {{baseUrl}}


###
# @name GetbyId
GET {{baseUrl}}/64c9ee2f999d05165d828c68

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
    "name":"demo",
    "album": {
        "_id": "64c9ee2f999d05165d828c68",
        "name": "demo",
        "slug": "demo"
    },
    "artists": [
        {
            "_id": "64c9ee2f999d05165d828c68",
            "name": "demo",
            "slug": "demo"
        }
    ],
    "composers": [
        {
            "_id": "64c9ee2f999d05165d828c68",
            "name": "demo",
            "slug": "demo"
        }
    ],
    "duration": 0,
    "imageUrl": "https://res.cloudinary.com/dqj3kgpoj/image/upload/v1626190249/albums/64c9ee2f999d05165d828c68/64c9ee2f999d05165d828c68.jpg",
    "audio_url": "https://res.cloudinary.com/dqj3kgpoj/video/upload/v1626190249/albums/64c9ee2f999d05165d828c68/64c9ee2f999d05165d828c68.mp3"
}

###

# @name Update
PUT {{baseUrl}}/update/64d364bcf1daaf1c65c96395
Content-Type: application/json

{
   "name": "demo mới"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/64d364bcf1daaf1c65c96395

###
###
# @name DeleteMany
POST {{baseUrl}}/delete-many
Content-Type: application/json

{
    "ids": [
        "64cb784edbeafd46df22e8b1",
        ]
}

###
# @name Trash
GET {{baseUrl}}/trash

###
# @name Restore
PATCH {{baseUrl}}/restore/64d364bcf1daaf1c65c96395

###
# @name ForceDelete
DELETE {{baseUrl}}/force/64d364b5f1daaf1c65c96392
