@baseUrl =  http://localhost:3000/api/songs

# User API

# @name Getall
GET {{baseUrl}} 

###
# @name GetallAlbums
POST {{baseUrl}}/albums
Content-Type: application/json

{
    "trackIds": [
        "64b3f1c6bfbea58867fd230b",
        "64b3f25bbfbea58867fd230d"
    ]
}
###


# @name GetbyId
GET {{baseUrl}}/64afc0d05f5748fd29c3e8d5

###

# @name Create
POST {{baseUrl}}/store
Content-Type: application/json

{
    "name":"Vì em chưa bao giờ khóc",
    "artists": [
        {
            "id": "64afc0d05f5748fd29c3e8d5",
            "name": "Ca sĩ 1"
        },{
            "id": "64afc0d05f5748fd29c3e8d6",
            "name": "Ca sĩ 2"
        }
    ],
    "duration": 200,
    "image_url": "/images/songs/10.webp",
    "audio_url": "https://firebasestorage.googleapis.com/v0/b/zingmp3-6bbfe.appspot.com/o/vi-em-chua-bao-gio-khoc.mp3?alt=media&token=79813ae7-b946-41d7-b13e-d709e0992586",
    "public": true,
    "artistId":"64b390058efd3f272746a780"
}

###

# @name Update
PUT {{baseUrl}}/update/6455ceffc8d917d3615a497a
Content-Type: application/json

{
   "name": "Đèn"
}

###

# @name Delete
DELETE {{baseUrl}}/delete/6455ceffc8d917d3615a497b

###